## Numpy Basic

In [ ]:
##  Command to install numpy
!pip install numpy

In [3]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
## 0D array
arr = np.array(42)
print(arr)

## 1D array
arr1 = np.array([1,2,3,4,6])
print(arr1)

## 2D array
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

42
[1 2 3 4 6]
[[1 2 3]
 [4 5 6]]


In [7]:
## Check no of dimensions
print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)

0
1
2


In [8]:
## Indexing in array
arr = np.array([1,2,3,4])

print(arr[0])

1


In [10]:
## Accesing 2D arrays
arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])

print("print 2nd element on 1st row ",arr[0,1])

print 2nd element on 1st row  2


In [11]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])

print("print last element on 2nd row ",arr[1,-1])

print last element on 2nd row  0


In [ ]:
## Numpy array slicing
arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])
## Return 1st to 3rd element from 1st index
print(arr[1, 1:4])

[7 8 9]


In [ ]:
## From both elements return index 2
print(arr[0:2, 2])

[3 8]


In [14]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [15]:
## Numpy datatypes
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [16]:
arr = np.array([1,2,3,4,5])

print(arr.dtype)

int32


In [17]:
## Converting datatype on existing arrays
arr = np.array([1.1, 2.2, 3.3])

newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [18]:
arr = np.array([1,0,3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [ ]:
## Numpy copy v/s view

## In copy the data is not changed in the copy array as orignal array owns the data
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 20

print(arr)
print(x)

## Changes the value in both orignal and copied array.
x = arr.view()
arr[0] = 20

print(arr)
print(x)

[20  2  3  4  5]
[1 2 3 4 5]
[20  2  3  4  5]
[20  2  3  4  5]


In [ ]:
## Numpy shapes
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [ ]:
## Numpy Reshaping
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3) ## 4 rows, 3 cols

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [24]:
arr = np.array([[1,2,3],[4,5,6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [25]:
## Numpy joining arrays
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr1,arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
## Joining arrays along rows
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1,arr2), axis=1)

In [27]:
## Numpy splitting arrays

arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [28]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [33]:
## Numpy searching values in array
arr = np.array([1,2,3,4,5,4,6])

x = np.where(arr == 4)
print(x)

(array([3, 5], dtype=int64),)


In [ ]:
## Find the indexes where the values are even
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [31]:
## searchsorted
arr = np.array([6,7,8,9])
x = np.searchsorted(arr, 7)
print(x)

1


In [ ]:
## Searching from right side
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')
print(x)

2


In [34]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])
print(x)

[1 2 3]


In [35]:
## Sorting arrays
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
