## Numpy Universal Functions

In [6]:
## Create your own universal function
import numpy as np
def myadd(x,y):
    return x+y

myadd = np.frompyfunc(myadd,2,1)
print(myadd([1,2,3,4,5],[5,6,7,8,9]))

[6 8 10 12 14]


In [ ]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)
print(newarr)

## similar methods
np.subtract()
np.multiply()
np.divide()

[30 32 34 36 38 40]


In [ ]:
## Power method
newarr = np.power(arr1, arr2)
print(newarr)

[ 1661992960   602408795           0  1487897765  1090519040 -1144744561]


In [10]:
## Quotient and mod
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


In [11]:
## absolute method
arr = np.array([-1,-2,1,3,-4])
newarr = np.absolute(arr)
print(newarr)

[1 2 1 3 4]


In [12]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)



Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [ ]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])